# Generated by Django 4.2.15 on 2024-08-16 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
