# Generated by Django 4.2.15 on 2024-08-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('o_plus', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_plus', models.DecimalField(decimal_places=3, max_digits=8)),
                ('b_plus', models.DecimalField(decimal_places=3, max_digits=8)),
                ('ab_plus', models.DecimalField(decimal_places=3, max_digits=8)),
                ('o_minus', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_minus', models.DecimalField(decimal_places=3, max_digits=8)),
                ('b_minus', models.DecimalField(decimal_places=3, max_digits=8)),
                ('ab_minus', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
    ]
